package fr.rsommerard.privacyaware.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import fr.rsommerard.privacyaware.dao.Data;
import fr.rsommerard.privacyaware.dao.Device;

import fr.rsommerard.privacyaware.dao.DataDao;
import fr.rsommerard.privacyaware.dao.DeviceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataDaoConfig;
    private final DaoConfig deviceDaoConfig;

    private final DataDao dataDao;
    private final DeviceDao deviceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataDaoConfig = daoConfigMap.get(DataDao.class).clone();
        dataDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        dataDao = new DataDao(dataDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);

        registerDao(Data.class, dataDao);
        registerDao(Device.class, deviceDao);
    }
    
    public void clear() {
        dataDaoConfig.getIdentityScope().clear();
        deviceDaoConfig.getIdentityScope().clear();
    }

    public DataDao getDataDao() {
        return dataDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

}
